[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "5xn2SZKTMMYdUsgLHChWyUQQnG2Wgs3MbGAZaykVmVDP"

[programs.devnet]
contracts = "5xn2SZKTMMYdUsgLHChWyUQQnG2Wgs3MbGAZaykVmVDP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/yieldos-devnet.json"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
