[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "9dEwdrEo7Tu9eTW3S3opbJa1fyyppRGPpdn8CqBxJX27"

[programs.devnet]
contracts = "9dEwdrEo7Tu9eTW3S3opbJa1fyyppRGPpdn8CqBxJX27"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/yieldos-devnet.json"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
create-strategy = "npx ts-node scripts/create-strategy.ts"
